/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js conventions and kept in source control so
// greenfield cloud builds can type-check before the first local dev boot.
