import type { AspirationEvidence, ChannelScore, ExperienceEvidence, JobResponsibility, QualificationEvidence, V3Fit, V3Job, V3Person } from "@/v3/types";
function identity(mapping:{level:string;selected:{taskId?:string|null;id?:string}|null}) { if(!mapping.selected)return null; return mapping.level==="task"?`task:${mapping.selected.taskId}`:mapping.level==="dwa"?`dwa:${mapping.selected.id}`:null; }
function identities(r:JobResponsibility){const set=new Set<string>(); const m=r.mapping;if(m.level==="task"&&m.selected&&"taskId" in m.selected)set.add(`task:${m.selected.taskId}`);for(const c of m.candidates.slice(0,1))for(const d of c.task.dwas)set.add(`dwa:${d.id}`);if(m.level==="dwa"&&m.selected&&"id" in m.selected)set.add(`dwa:${m.selected.id}`);return set;}
function match(mapping:{level:string;selected:object|null;candidates:{task:{dwas:{id:string}[]}}[]}, job:JobResponsibility){const id=identity(mapping as never);if(id&&identities(job).has(id))return id.startsWith("task:")?1:.6;return 0;}
export function preferenceFit(person:V3Person,job:V3Job):ChannelScore {const known=person.preferences.filter(p=>p.stance!=="UNKNOWN");const contributions=known.flatMap(p=>job.responsibilities.map(r=>{const m=match(p.mapping,r);if(!m)return null;const s=p.strength??1;return p.stance==="LIKE"?m*s:p.stance==="DISLIKE"?-m*s:0;})).filter((x):x is number=>x!==null);return {channel:"preference",score:contributions.length?clamp(.5+sum(contributions)/(2*contributions.length)):null,coverage:job.responsibilities.length?new Set(known.flatMap(p=>job.responsibilities.filter(r=>match(p.mapping,r)>0).map(r=>r.id))).size/job.responsibilities.length:0,evidenceCount:known.length,diagnostics:["UNKNOWN excluded; NEUTRAL contributes zero; absence of LIKE is not DISLIKE"]};}
export function experienceFit(person:V3Person,job:V3Job):ChannelScore {const dedup=dedupeExperience(person.experience);const covered=job.responsibilities.map(r=>Math.max(0,...dedup.map(e=>match(e.mapping,r)*strength(e)*ownership(e))));return {channel:"experience",score:covered.length&&dedup.length?mean(covered):null,coverage:covered.length?covered.filter(x=>x>0).length/covered.length:0,evidenceCount:dedup.length,diagnostics:["common-source evidence deduplicated","DWA partial credit=0.6"]};}
export function qualificationFit(person:V3Person,job:V3Job,aliases:AliasProvider=DEFAULT_ALIASES):ChannelScore {const active=person.qualifications.filter(q=>!q.negated);const reqs=job.requirements.filter(r=>!r.negated);const results=reqs.map(r=>active.some(q=>equivalent(q,r.value,r.kind,aliases)));const required=reqs.map((r,i)=>({r,ok:results[i]!})).filter(x=>x.r.required),preferred=reqs.map((r,i)=>({r,ok:results[i]!})).filter(x=>!x.r.required);const hardGaps=required.filter(x=>!x.ok).length;const denominator=required.length+preferred.length*.25;const positive=required.filter(x=>x.ok).length+preferred.filter(x=>x.ok).length*.25;return {channel:"qualification",score:denominator?positive/denominator:null,coverage:reqs.length?results.filter(Boolean).length/reqs.length:0,evidenceCount:active.length,diagnostics:[`hardGaps=${hardGaps}`,"preferred requirement weight=0.25","negated evidence does not satisfy requirements"]};}
export function directionFit(person:V3Person,job:V3Job):ChannelScore {return mappedAlignment("direction",person.aspirations,job);}
function mappedAlignment(channel:"direction",evidence:AspirationEvidence[],job:V3Job):ChannelScore{const matches=job.responsibilities.map(r=>Math.max(0,...evidence.map(e=>match(e.mapping,r)*(e.strength??1))));return {channel,score:matches.length&&evidence.length?mean(matches):null,coverage:matches.length?matches.filter(x=>x>0).length/matches.length:0,evidenceCount:evidence.length,diagnostics:["aspiration is not capability or experience"]};}
export function scoreV3(person:V3Person,job:V3Job):V3Fit{return {preference:preferenceFit(person,job),experience:experienceFit(person,job),qualification:qualificationFit(person,job),direction:directionFit(person,job)};}
export interface AliasProvider{version:string;canonical(value:string):string}
const GROUPS=[["js","javascript"],["ts","typescript"],["python programming","python"],["bachelors degree","bachelor degree","bachelor's degree","bs"],["masters degree","master degree","master's degree","ms"]];
export const DEFAULT_ALIASES:AliasProvider={version:"qualification-aliases.v1",canonical(value){const n=normalize(value);return GROUPS.find(g=>g.includes(n))?.[0]??n;}};
export function normalize(value:string){return value.toLowerCase().normalize("NFKD").replace(/[^a-z0-9+#]+/g," ").trim().replace(/\s+/g," ");}
function equivalent(q:QualificationEvidence,value:string,kind:string,a:AliasProvider){return q.kind===kind&&a.canonical(q.value)===a.canonical(value);}
function dedupeExperience(xs:ExperienceEvidence[]){const seen=new Set<string>();return xs.filter(x=>{const key=`${x.sourceGroup}:${identity(x.mapping)}`;if(seen.has(key))return false;seen.add(key);return true;});}
const strength=(x:ExperienceEvidence)=>x.strength==="deep" ? 1 : x.strength==="demonstrated" ? .75 : .4;
const ownership=(x:ExperienceEvidence)=>x.ownership==="led" ? 1 : x.ownership==="performed" ? .85 : x.ownership==="assisted" ? .55 : .65;
const clamp=(x:number)=>Math.max(0,Math.min(1,x));const sum=(x:number[])=>x.reduce((a,b)=>a+b,0);const mean=(x:number[])=>x.length?sum(x)/x.length:0;
