import type { CareerFunction, DimensionId, TaskDimensionDefinition, Vector } from "@/domain/types";

export const DIMENSION_IDS: DimensionId[] = [
  "problem_structure",
  "measurable_feedback",
  "investigation_orientation",
  "evidence_density",
  "experimentation_preference",
  "scope_preference",
  "software_as_tool",
  "reasoning_style",
  "creation_style",
  "real_system_grounding",
  "closure_preference",
  "causal_reasoning",
  "integration_preference",
  "customer_interaction_preference",
  "coordination_preference",
  "theory_vs_application",
  "repetition_tolerance",
];

export const dimensions: TaskDimensionDefinition[] = [
  ["problem_structure", "Problem structure", "bounded and diagnosable", "open-ended and poorly scoped", "Defined vs ambiguous"],
  ["measurable_feedback", "Measurable feedback", "observable feedback loops", "long uncertain feedback loops", "Measurable signal"],
  ["investigation_orientation", "Investigation orientation", "diagnose, test, improve", "document, coordinate, administer", "Investigative work"],
  ["evidence_density", "Evidence density", "logs, signals, measurements", "administrative information", "Evidence-rich work"],
  ["experimentation_preference", "Experimentation preference", "targeted experiments", "rote execution", "Experimentation"],
  ["scope_preference", "Scope preference", "bounded subsystems", "massive ambiguous systems", "Bounded scope"],
  ["software_as_tool", "Software as tool", "software used to solve another problem", "software detached from a real system", "Software as tool"],
  ["reasoning_style", "Reasoning style", "hypothesis and causality", "memorization and compliance", "Causal reasoning"],
  ["creation_style", "Creation style", "constrained creation", "blank-sheet invention", "Constrained creation"],
  ["real_system_grounding", "Real system grounding", "physical or observable systems", "abstract process only", "Real-world grounding"],
  ["closure_preference", "Closure preference", "verify and close the loop", "endless exploration", "Closure"],
  ["causal_reasoning", "Causal reasoning", "why did this happen", "what happened", "Root cause"],
  ["integration_preference", "Integration preference", "connect systems and evidence streams", "isolated work", "Integration"],
  ["customer_interaction_preference", "Customer interaction preference", "field/customer interaction", "internal technical work", "Customer exposure"],
  ["coordination_preference", "Coordination preference", "stakeholder orchestration", "individual deep investigation", "Coordination"],
  ["theory_vs_application", "Theory vs application", "applied behavior and testing", "theoretical abstraction", "Applied work"],
  ["repetition_tolerance", "Repetition tolerance", "routine workflows acceptable", "novel problem solving preferred", "Routine tolerance"],
].map(([id, label, high, low, consumerLabel]) => ({ id, label, high, low, consumerLabel })) as TaskDimensionDefinition[];

export function vector(values: Partial<Vector>): Vector {
  return Object.fromEntries(DIMENSION_IDS.map((id) => [id, values[id] ?? 5])) as Vector;
}

export const scoringConfig = {
  version: "scoring.v1",
  confidenceAdjustedFitPenalty: 2,
  weights: {
    hireability: 0.4,
    confidenceAdjustedFit: 0.3,
    careerDirection: 0.15,
    technicalGrowth: 0.1,
    durability: 0.05,
  },
  tiers: {
    attackFirst: { overall: 8.2, hireability: 7.5, fit: 8.4 },
    coreApply: { hireability: 7.5 },
    highFitStretch: { hireabilityMin: 6.5, hireabilityMax: 7.49, fit: 8.7, confidence: 0.65 },
  },
  featureFlags: {
    experimentalScoring: false,
    adaptiveInterview: true,
    noveltyScoring: true,
    negativeFitModel: true,
    activeLearning: true,
  },
} as const;

export const careerFunctions: CareerFunction[] = [
  {
    id: "failure-analysis",
    name: "Failure Analysis / Reliability / Sustaining R&D",
    shortName: "Failure analysis",
    oneSentenceTaskLoop: "Investigate why real products fail, gather evidence, test hypotheses, and close the loop with fixes.",
    longerDescription: "Evidence-rich root-cause work across logs, hardware, test data, and manufacturing or field signals.",
    taskDnaVector: vector({ investigation_orientation: 9.6, evidence_density: 9.1, experimentation_preference: 8.6, causal_reasoning: 9.7, closure_preference: 9.2, real_system_grounding: 8.9, repetition_tolerance: 4.2 }),
    commonAttractors: ["root cause", "telemetry", "test evidence", "closed-loop fixes"],
    commonRepellents: ["urgent escalations", "documentation tail", "messy ownership"],
    typicalTitles: ["Failure Analysis Engineer", "Reliability Engineer", "Product Performance Engineer"],
    typicalDomains: ["medical devices", "semiconductors", "aerospace", "manufacturing"],
    typicalRequirements: ["debugging", "statistics", "test design", "technical writing"],
    commonSkillGaps: ["formal reliability methods", "domain-specific test equipment"],
    active: true,
    version: "function.v1",
  },
  {
    id: "sensor-algorithm-performance",
    name: "Sensor & Algorithm Performance",
    shortName: "Sensor performance",
    oneSentenceTaskLoop: "Use data and experiments to understand where sensing or algorithm behavior succeeds and fails.",
    longerDescription: "Applied data work that ties model behavior to real-world signal quality, cohorts, instrumentation, and edge cases.",
    taskDnaVector: vector({ measurable_feedback: 9.2, evidence_density: 9.4, experimentation_preference: 8.8, software_as_tool: 8.7, real_system_grounding: 8.3, theory_vs_application: 8.5, causal_reasoning: 8.8 }),
    commonAttractors: ["signals", "performance metrics", "subgroup analysis", "algorithm debugging"],
    commonRepellents: ["unclear labels", "production data access friction"],
    typicalTitles: ["Algorithm Performance Engineer", "Sensor Data Scientist", "Clinical Algorithm Analyst"],
    typicalDomains: ["healthcare", "robotics", "scientific instrumentation"],
    typicalRequirements: ["Python", "data analysis", "signal processing", "statistics"],
    commonSkillGaps: ["regulated ML validation", "advanced signal processing"],
    active: true,
    version: "function.v1",
  },
  {
    id: "test-development",
    name: "Test Development & Performance Characterization",
    shortName: "Test development",
    oneSentenceTaskLoop: "Build test methods and experiments that reveal system behavior under meaningful conditions.",
    longerDescription: "A mix of experimental design, instrumentation, automation, analysis, and actionable characterization.",
    taskDnaVector: vector({ problem_structure: 8.3, measurable_feedback: 9.3, experimentation_preference: 9.2, real_system_grounding: 8.4, closure_preference: 8.6, software_as_tool: 7.4 }),
    commonAttractors: ["test design", "measurement", "automation", "performance envelopes"],
    commonRepellents: ["protocol repetition", "equipment scheduling"],
    typicalTitles: ["Test Development Engineer", "Characterization Engineer", "Verification Tools Engineer"],
    typicalDomains: ["medical devices", "robotics", "energy", "aerospace"],
    typicalRequirements: ["instrumentation", "Python", "DOE", "data visualization"],
    commonSkillGaps: ["hardware fixtures", "formal validation protocols"],
    active: true,
    version: "function.v1",
  },
  {
    id: "systems-integration-debug",
    name: "Systems Integration & Real-World Debug",
    shortName: "Systems debug",
    oneSentenceTaskLoop: "Trace cross-layer failures that only appear when hardware, software, sensors, and users meet.",
    longerDescription: "Integration troubleshooting across interfaces, logs, field signals, and experiments.",
    taskDnaVector: vector({ investigation_orientation: 9.2, integration_preference: 9.7, real_system_grounding: 9.4, evidence_density: 8.8, scope_preference: 8.2, customer_interaction_preference: 5.8, causal_reasoning: 9.1 }),
    commonAttractors: ["cross-layer debug", "system behavior", "field evidence", "interfaces"],
    commonRepellents: ["unclear ownership", "travel spikes", "interrupt-driven work"],
    typicalTitles: ["Systems Integration Engineer", "Field Performance Engineer", "Systems Test Engineer"],
    typicalDomains: ["robotics", "aerospace", "automation", "medical devices"],
    typicalRequirements: ["systems thinking", "logging", "test planning", "hardware/software fluency"],
    commonSkillGaps: ["embedded C++", "controls fundamentals"],
    active: true,
    version: "function.v1",
  },
  {
    id: "engineering-tools",
    name: "Engineering Tools / Automation / Data Integration",
    shortName: "Engineering tools",
    oneSentenceTaskLoop: "Turn tedious engineering workflows into reliable tools that connect data and reduce manual reconciliation.",
    longerDescription: "Software-building with a concrete engineering or scientific workflow as the customer.",
    taskDnaVector: vector({ software_as_tool: 9.8, creation_style: 8.4, measurable_feedback: 8.1, integration_preference: 8.5, evidence_density: 7.9, customer_interaction_preference: 4.2, repetition_tolerance: 5.1 }),
    commonAttractors: ["automation", "workflow design", "data integration", "usable internal tools"],
    commonRepellents: ["generic web backlog", "stakeholder churn"],
    typicalTitles: ["Engineering Tools Engineer", "Scientific Software Engineer", "Data Automation Engineer"],
    typicalDomains: ["software", "scientific instrumentation", "manufacturing", "healthcare"],
    typicalRequirements: ["TypeScript or Python", "data modeling", "UX empathy", "APIs"],
    commonSkillGaps: ["production frontend depth", "database operations"],
    active: true,
    version: "function.v1",
  },
  {
    id: "clinical-real-world-performance",
    name: "Clinical / Real-World Algorithm Performance",
    shortName: "Real-world performance",
    oneSentenceTaskLoop: "Investigate how technical systems perform across messy real-world populations and contexts.",
    longerDescription: "Applied evidence work that separates algorithm behavior, workflow effects, and data quality.",
    taskDnaVector: vector({ evidence_density: 8.7, investigation_orientation: 8.9, theory_vs_application: 8.8, customer_interaction_preference: 5.6, causal_reasoning: 8.5, real_system_grounding: 8.7 }),
    commonAttractors: ["real-world data", "performance drift", "equity questions", "clinical workflow evidence"],
    commonRepellents: ["privacy constraints", "slow institutional cycles"],
    typicalTitles: ["Clinical Data Scientist", "Real-World Performance Analyst", "Algorithm Evaluation Engineer"],
    typicalDomains: ["healthcare", "medical devices", "digital health"],
    typicalRequirements: ["Python", "statistics", "health data literacy", "careful communication"],
    commonSkillGaps: ["clinical domain knowledge", "HIPAA production practices"],
    active: true,
    version: "function.v1",
  },
  {
    id: "field-applications",
    name: "Technical Field Service / Applications",
    shortName: "Field applications",
    oneSentenceTaskLoop: "Solve technical issues with customers in the field and translate patterns back to product teams.",
    longerDescription: "Customer-facing troubleshooting with real systems, fast feedback, and communication demands.",
    taskDnaVector: vector({ real_system_grounding: 9, investigation_orientation: 8.2, customer_interaction_preference: 9.3, closure_preference: 8.2, coordination_preference: 7.2, evidence_density: 7.4 }),
    commonAttractors: ["hands-on troubleshooting", "fast feedback", "customer context"],
    commonRepellents: ["travel", "interrupts", "emotional escalation"],
    typicalTitles: ["Applications Engineer", "Field Service Engineer", "Technical Support Engineer"],
    typicalDomains: ["scientific instrumentation", "automation", "robotics", "medical devices"],
    typicalRequirements: ["communication", "system troubleshooting", "travel readiness"],
    commonSkillGaps: ["customer escalation handling", "onsite availability"],
    active: true,
    version: "function.v1",
  },
  {
    id: "robotics-field-performance",
    name: "Robotics / Autonomy Field Performance",
    shortName: "Robotics performance",
    oneSentenceTaskLoop: "Diagnose robot behavior in real environments and improve sensing, autonomy, and operations.",
    longerDescription: "High-fit for people who like embodied systems, logs, experiments, and cross-layer behavior.",
    taskDnaVector: vector({ real_system_grounding: 9.7, integration_preference: 9.3, evidence_density: 8.9, experimentation_preference: 8.8, software_as_tool: 8.4, causal_reasoning: 9 }),
    commonAttractors: ["robots in the world", "logs", "field experiments", "autonomy edge cases"],
    commonRepellents: ["C++/embedded barriers", "field operations", "hardware constraints"],
    typicalTitles: ["Robotics Field Performance Engineer", "Autonomy Test Engineer", "Robot Reliability Engineer"],
    typicalDomains: ["robotics", "automation", "aerospace"],
    typicalRequirements: ["Python", "C++", "robotics logs", "controls basics"],
    commonSkillGaps: ["C++", "ROS", "embedded systems"],
    active: true,
    version: "function.v1",
  },
  {
    id: "controls-characterization",
    name: "Controls & System Characterization",
    shortName: "Controls characterization",
    oneSentenceTaskLoop: "Characterize dynamic systems and tune or validate behavior using models and experiments.",
    longerDescription: "Applied controls work anchored in measured behavior rather than pure theory.",
    taskDnaVector: vector({ theory_vs_application: 7.5, measurable_feedback: 8.8, real_system_grounding: 9, experimentation_preference: 8.1, causal_reasoning: 8.4, problem_structure: 7.6 }),
    commonAttractors: ["dynamic behavior", "models plus data", "tuning", "verification"],
    commonRepellents: ["math-heavy abstraction", "specialized tooling"],
    typicalTitles: ["Controls Engineer", "System Characterization Engineer", "Dynamics Test Engineer"],
    typicalDomains: ["aerospace", "energy", "robotics", "medical devices"],
    typicalRequirements: ["controls", "MATLAB/Python", "data acquisition"],
    commonSkillGaps: ["formal control theory", "embedded implementation"],
    active: true,
    version: "function.v1",
  },
  {
    id: "scientific-software",
    name: "Scientific Software",
    shortName: "Scientific software",
    oneSentenceTaskLoop: "Build software that makes scientific or technical evidence easier to analyze, simulate, and use.",
    longerDescription: "Software creation tied to scientific workflows, models, instrumentation, or data interpretation.",
    taskDnaVector: vector({ software_as_tool: 9.5, creation_style: 8.7, evidence_density: 8.2, theory_vs_application: 7.7, customer_interaction_preference: 3.8, integration_preference: 7.8 }),
    commonAttractors: ["domain software", "data tools", "simulation support", "usable analysis"],
    commonRepellents: ["pure SaaS feature churn", "unclear scientific validation"],
    typicalTitles: ["Scientific Software Engineer", "Research Software Engineer", "Computational Tools Developer"],
    typicalDomains: ["scientific instrumentation", "healthcare", "energy", "analytics"],
    typicalRequirements: ["Python", "numerical methods", "data visualization", "testing"],
    commonSkillGaps: ["production software architecture", "domain-specific math"],
    active: true,
    version: "function.v1",
  },
  {
    id: "verification-validation",
    name: "Verification / Validation / Software Test",
    shortName: "V&V",
    oneSentenceTaskLoop: "Confirm systems meet requirements through protocols, tests, traceability, and documented evidence.",
    longerDescription: "Important but often documentation-heavy work, distinct from exploratory failure analysis.",
    taskDnaVector: vector({ problem_structure: 9.1, closure_preference: 8.6, repetition_tolerance: 8.8, coordination_preference: 6.8, investigation_orientation: 4.8, experimentation_preference: 4.9, evidence_density: 6.3 }),
    commonAttractors: ["clear requirements", "quality evidence", "release confidence"],
    commonRepellents: ["rote protocols", "traceability", "documentation load"],
    typicalTitles: ["V&V Engineer", "Software Test Engineer", "Design Verification Engineer"],
    typicalDomains: ["medical devices", "aerospace", "software", "manufacturing"],
    typicalRequirements: ["test protocols", "requirements", "documentation", "quality systems"],
    commonSkillGaps: ["regulatory context", "automation frameworks"],
    active: true,
    version: "function.v1",
  },
  {
    id: "modeling-simulation",
    name: "Modeling / Simulation / Digital Twins",
    shortName: "Modeling",
    oneSentenceTaskLoop: "Create and calibrate models that explain or predict technical system behavior.",
    longerDescription: "Can be high-fit for theory-friendly users, but too abstract for those needing fast real-world feedback.",
    taskDnaVector: vector({ theory_vs_application: 4.4, measurable_feedback: 5.6, creation_style: 8.1, evidence_density: 7.4, problem_structure: 5.5, closure_preference: 5.2 }),
    commonAttractors: ["models", "simulation", "technical depth", "abstraction"],
    commonRepellents: ["long validation loops", "theory-heavy work"],
    typicalTitles: ["Modeling Engineer", "Simulation Engineer", "Digital Twin Engineer"],
    typicalDomains: ["aerospace", "energy", "manufacturing", "robotics"],
    typicalRequirements: ["math modeling", "simulation tools", "domain physics"],
    commonSkillGaps: ["advanced math", "specialized simulation packages"],
    active: true,
    version: "function.v1",
  },
  {
    id: "product-systems-engineering",
    name: "Broad Product R&D / Systems Engineering",
    shortName: "Product systems",
    oneSentenceTaskLoop: "Shape broad product direction, requirements, interfaces, and tradeoffs across teams.",
    longerDescription: "Valuable work, but often ambiguous and coordination-heavy compared with hands-on investigation.",
    taskDnaVector: vector({ problem_structure: 4.2, coordination_preference: 9.1, customer_interaction_preference: 7.2, integration_preference: 8.4, investigation_orientation: 5.4, closure_preference: 4.9 }),
    commonAttractors: ["strategy", "interfaces", "product tradeoffs", "cross-functional influence"],
    commonRepellents: ["ambiguity", "requirements churn", "meetings"],
    typicalTitles: ["Systems Engineer", "Product Systems Engineer", "Technical Product Manager"],
    typicalDomains: ["medical devices", "aerospace", "software", "automation"],
    typicalRequirements: ["requirements", "stakeholder communication", "systems thinking"],
    commonSkillGaps: ["formal systems engineering", "domain standards"],
    active: true,
    version: "function.v1",
  },
];
