import type { AskType, Channel, NetworkingPrinciple, RelationshipType } from "@/domain/networkTypes";

export const networkModelConfig = {
  versions: {
    networkSchema: "network.schema.v1",
    relationshipInference: "relationship.inference.v1",
    readinessRules: "readiness.v1",
    strategyModel: "human.strategy.v1",
    askOntology: "ask.ontology.v1",
    pathScoring: "path.scoring.v1",
    actionScoring: "action.priority.v1",
    principleRegistry: "principles.v1",
    messageComposer: "message.composer.v1",
    executionPolicy: "execution.policy.v1",
  },
  accessWeights: {
    information: 0.25,
    routing: 0.25,
    credibility: 0.22,
    advocacy: 0.18,
    secondDegree: 0.1,
  },
  pathWeights: {
    destinationRelevance: 0.22,
    firstHopReadiness: 0.2,
    edgeCertainty: 0.14,
    routingPlausibility: 0.14,
    credibilityTransfer: 0.1,
    advocacyPotential: 0.08,
    currentOrgRelevance: 0.07,
    confidence: 0.05,
    hopPenalty: 0.75,
    socialCostPenalty: 0.18,
  },
  actionWeights: {
    intrinsicOpportunityPriority: 0.26,
    expectedAccessGain: 0.2,
    informationGain: 0.12,
    urgency: 0.12,
    readiness: 0.14,
    strategicNetworkValue: 0.08,
    careerDirectionValue: 0.08,
    socialCostPenalty: 0.18,
    timeCostPenalty: 0.06,
  },
  relationshipDefaults: {
    FORMER_MANAGER: { information: 7, routing: 5, credibility: 9, advocacy: 8, socialCost: 4 },
    FORMER_COWORKER: { information: 7, routing: 6, credibility: 7, advocacy: 5, socialCost: 4 },
    PROFESSOR: { information: 8, routing: 6, credibility: 7, advocacy: 5, socialCost: 5 },
    MENTOR: { information: 8, routing: 7, credibility: 6, advocacy: 5, socialCost: 4 },
    ALUM: { information: 7, routing: 7, credibility: 2, advocacy: 1, socialCost: 3 },
    INDUSTRY_CONTACT: { information: 7, routing: 6, credibility: 3, advocacy: 2, socialCost: 4 },
    RECRUITER: { information: 8, routing: 8, credibility: 2, advocacy: 4, socialCost: 2 },
    DORMANT_FORMER_STRONG_TIE: { information: 7, routing: 6, credibility: 8, advocacy: 6, socialCost: 5 },
    SECOND_DEGREE: { information: 5, routing: 7, credibility: 1, advocacy: 0.5, socialCost: 5 },
    COLD_CONTEXTUAL_CONTACT: { information: 5, routing: 4, credibility: 0.5, advocacy: 0, socialCost: 5 },
  } satisfies Partial<Record<RelationshipType, { information: number; routing: number; credibility: number; advocacy: number; socialCost: number }>>,
} as const;

export const askRules: Record<AskType, {
  socialCost: number;
  timeBurden: number;
  credibilityRequirement: number;
  relationshipRequirement: number;
  opportunitySpecificity: number;
  urgencyCompatibility: number;
  channelCompatibility: Channel[];
  prerequisites: string[];
  escalationPotential: number;
  riskFlags: string[];
}> = {
  RECONNECT: { socialCost: 2, timeBurden: 2, credibilityRequirement: 1, relationshipRequirement: 2, opportunitySpecificity: 0, urgencyCompatibility: 3, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL", "TEXT"], prerequisites: ["authentic shared context"], escalationPotential: 5, riskFlags: ["avoid fake pretext"] },
  CATCH_UP: { socialCost: 3, timeBurden: 5, credibilityRequirement: 1, relationshipRequirement: 4, opportunitySpecificity: 0, urgencyCompatibility: 2, channelCompatibility: ["EMAIL", "TEXT", "PHONE", "VIDEO"], prerequisites: ["warm enough relationship"], escalationPotential: 5, riskFlags: [] },
  CAREER_PERSPECTIVE: { socialCost: 3, timeBurden: 4, credibilityRequirement: 1, relationshipRequirement: 2, opportunitySpecificity: 1, urgencyCompatibility: 4, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL", "VIDEO"], prerequisites: [], escalationPotential: 5, riskFlags: [] },
  FUNCTION_INSIGHT: { socialCost: 3, timeBurden: 4, credibilityRequirement: 1, relationshipRequirement: 2, opportunitySpecificity: 3, urgencyCompatibility: 5, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL", "VIDEO"], prerequisites: ["function relevance"], escalationPotential: 6, riskFlags: [] },
  ROLE_REALITY: { socialCost: 3, timeBurden: 3, credibilityRequirement: 1, relationshipRequirement: 1, opportunitySpecificity: 7, urgencyCompatibility: 7, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL"], prerequisites: ["role exists"], escalationPotential: 5, riskFlags: [] },
  COMPANY_INFORMATION: { socialCost: 3, timeBurden: 3, credibilityRequirement: 1, relationshipRequirement: 1, opportunitySpecificity: 4, urgencyCompatibility: 7, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL"], prerequisites: ["company relevance"], escalationPotential: 5, riskFlags: [] },
  TEAM_INFORMATION: { socialCost: 4, timeBurden: 4, credibilityRequirement: 1, relationshipRequirement: 2, opportunitySpecificity: 6, urgencyCompatibility: 7, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL"], prerequisites: ["team proximity"], escalationPotential: 6, riskFlags: [] },
  SKILL_ADVICE: { socialCost: 2, timeBurden: 3, credibilityRequirement: 1, relationshipRequirement: 1, opportunitySpecificity: 2, urgencyCompatibility: 4, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL"], prerequisites: ["skill relevance"], escalationPotential: 3, riskFlags: [] },
  FIT_REALITY_CHECK: { socialCost: 4, timeBurden: 4, credibilityRequirement: 3, relationshipRequirement: 3, opportunitySpecificity: 6, urgencyCompatibility: 6, channelCompatibility: ["EMAIL", "VIDEO"], prerequisites: ["contact understands function or user"], escalationPotential: 5, riskFlags: [] },
  WHO_SHOULD_I_TALK_TO: { socialCost: 3, timeBurden: 3, credibilityRequirement: 1, relationshipRequirement: 2, opportunitySpecificity: 4, urgencyCompatibility: 6, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL"], prerequisites: ["routing plausibility"], escalationPotential: 7, riskFlags: [] },
  INTRODUCTION_REQUEST: { socialCost: 6, timeBurden: 4, credibilityRequirement: 3, relationshipRequirement: 4, opportunitySpecificity: 6, urgencyCompatibility: 7, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL"], prerequisites: ["target person known", "reasonable burden"], escalationPotential: 8, riskFlags: ["do not ask weak tie for credibility"] },
  SECOND_DEGREE_INTRO_REQUEST: { socialCost: 6, timeBurden: 4, credibilityRequirement: 2, relationshipRequirement: 4, opportunitySpecificity: 6, urgencyCompatibility: 7, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL"], prerequisites: ["first-hop readiness"], escalationPotential: 8, riskFlags: ["ask first-hop only"] },
  REFERRAL_REQUEST: { socialCost: 8, timeBurden: 4, credibilityRequirement: 7, relationshipRequirement: 6, opportunitySpecificity: 8, urgencyCompatibility: 8, channelCompatibility: ["EMAIL"], prerequisites: ["credible work observation"], escalationPotential: 9, riskFlags: ["respect boundaries", "avoid fabricating credibility"] },
  RESUME_FORWARD_REQUEST: { socialCost: 7, timeBurden: 3, credibilityRequirement: 5, relationshipRequirement: 5, opportunitySpecificity: 8, urgencyCompatibility: 8, channelCompatibility: ["EMAIL"], prerequisites: ["specific role"], escalationPotential: 8, riskFlags: [] },
  HIRING_MANAGER_INTRO_REQUEST: { socialCost: 8, timeBurden: 5, credibilityRequirement: 6, relationshipRequirement: 6, opportunitySpecificity: 8, urgencyCompatibility: 8, channelCompatibility: ["EMAIL"], prerequisites: ["credible path"], escalationPotential: 9, riskFlags: ["high burden"] },
  RECRUITER_INTRO_REQUEST: { socialCost: 6, timeBurden: 3, credibilityRequirement: 3, relationshipRequirement: 4, opportunitySpecificity: 7, urgencyCompatibility: 8, channelCompatibility: ["EMAIL"], prerequisites: ["recruiter relevance"], escalationPotential: 7, riskFlags: [] },
  REFERENCE_REQUEST: { socialCost: 8, timeBurden: 5, credibilityRequirement: 8, relationshipRequirement: 7, opportunitySpecificity: 7, urgencyCompatibility: 7, channelCompatibility: ["EMAIL", "PHONE"], prerequisites: ["strong observed work"], escalationPotential: 8, riskFlags: ["high trust requirement"] },
  HIDDEN_OPPORTUNITY_QUERY: { socialCost: 4, timeBurden: 3, credibilityRequirement: 1, relationshipRequirement: 2, opportunitySpecificity: 3, urgencyCompatibility: 5, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL"], prerequisites: ["company or function relevance"], escalationPotential: 6, riskFlags: ["do not present rumors as jobs"] },
  APPLICATION_STATUS_HELP: { socialCost: 5, timeBurden: 3, credibilityRequirement: 2, relationshipRequirement: 3, opportunitySpecificity: 9, urgencyCompatibility: 8, channelCompatibility: ["EMAIL"], prerequisites: ["application submitted"], escalationPotential: 5, riskFlags: [] },
  POST_APPLICATION_NOTE: { socialCost: 4, timeBurden: 2, credibilityRequirement: 1, relationshipRequirement: 2, opportunitySpecificity: 9, urgencyCompatibility: 9, channelCompatibility: ["EMAIL"], prerequisites: ["application submitted"], escalationPotential: 5, riskFlags: [] },
  FOLLOW_UP: { socialCost: 3, timeBurden: 1, credibilityRequirement: 0, relationshipRequirement: 1, opportunitySpecificity: 4, urgencyCompatibility: 6, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL", "TEXT"], prerequisites: ["prior outreach"], escalationPotential: 4, riskFlags: ["limit repeated followups"] },
  THANK_YOU: { socialCost: 1, timeBurden: 1, credibilityRequirement: 0, relationshipRequirement: 0, opportunitySpecificity: 0, urgencyCompatibility: 8, channelCompatibility: ["EMAIL", "TEXT", "LINKEDIN_MANUAL"], prerequisites: ["help received"], escalationPotential: 2, riskFlags: [] },
  RELATIONSHIP_MAINTENANCE: { socialCost: 2, timeBurden: 2, credibilityRequirement: 0, relationshipRequirement: 2, opportunitySpecificity: 0, urgencyCompatibility: 1, channelCompatibility: ["EMAIL", "TEXT", "LINKEDIN_MANUAL"], prerequisites: ["authentic reason"], escalationPotential: 3, riskFlags: ["no fake pretexts"] },
  SHARE_USEFUL_RESOURCE: { socialCost: 2, timeBurden: 2, credibilityRequirement: 0, relationshipRequirement: 2, opportunitySpecificity: 1, urgencyCompatibility: 2, channelCompatibility: ["EMAIL", "LINKEDIN_MANUAL"], prerequisites: ["actually useful resource"], escalationPotential: 3, riskFlags: ["no performative networking"] },
  SCHEDULE_CONVERSATION: { socialCost: 4, timeBurden: 5, credibilityRequirement: 1, relationshipRequirement: 3, opportunitySpecificity: 3, urgencyCompatibility: 5, channelCompatibility: ["EMAIL", "TEXT"], prerequisites: ["conversation likely useful"], escalationPotential: 6, riskFlags: [] },
  SEND_REQUESTED_MATERIAL: { socialCost: 1, timeBurden: 2, credibilityRequirement: 0, relationshipRequirement: 0, opportunitySpecificity: 8, urgencyCompatibility: 9, channelCompatibility: ["EMAIL"], prerequisites: ["explicit request or offer"], escalationPotential: 9, riskFlags: [] },
};

export const channelExecutionPolicy: Record<Channel, ExecutionMode> = {
  EMAIL: "DRAFT_ONLY",
  LINKEDIN_MANUAL: "MANUAL_SEND",
  TEXT: "MANUAL_SEND",
  PHONE: "MANUAL_SEND",
  VIDEO: "MANUAL_SEND",
  IN_PERSON: "MANUAL_SEND",
  OTHER: "DRAFT_ONLY",
};

export const networkingPrinciples: NetworkingPrinciple[] = [
  {
    id: "weak-ties-job-transmission",
    title: "Moderately weak ties can be valuable for job transmission",
    principle: "Weak ties may transmit novel job information; strongest tie is not always best.",
    evidenceGrade: "A",
    evidenceType: "causal field experiment",
    sourceTitle: "A Causal Test of the Strength of Weak Ties",
    sourceAuthors: "Rajkumar et al.",
    sourceYear: 2022,
    sourceIdentifier: "DOI 10.1126/science.abl4476",
    applicableContext: "job information discovery and weak-tie routing",
    exceptions: ["credibility and advocacy still require observed work"],
    productImplication: "Score information/routing separately from credibility/advocacy.",
    version: "principle.v1",
    active: true,
  },
  {
    id: "dormant-ties",
    title: "Dormant ties can retain value",
    principle: "Previously strong dormant ties may combine trust, shared history, and novelty.",
    evidenceGrade: "B",
    evidenceType: "organizational research",
    sourceTitle: "Dormant Ties: The Value of Reconnecting",
    sourceAuthors: "Levin, Walter, Murnighan",
    sourceYear: 2011,
    sourceIdentifier: "DOI 10.1287/orsc.1100.0576",
    applicableContext: "reconnecting with former managers, professors, coworkers",
    exceptions: ["explicit boundaries and ask fatigue override"],
    productImplication: "Do not treat dormant former strong ties as strangers.",
    version: "principle.v1",
    active: true,
  },
  {
    id: "referral-information",
    title: "Referrals can carry unobserved candidate information",
    principle: "Referrals may convey information about persistence or capability not visible in applications.",
    evidenceGrade: "B",
    evidenceType: "field experiments and labor research",
    sourceTitle: "Referrals and hiring field experiments",
    sourceAuthors: "Pallais and Sands",
    sourceYear: 2015,
    sourceIdentifier: "NBER Working Paper 21357",
    applicableContext: "credible referral decisions",
    exceptions: ["weak contacts cannot credibly vouch without observed work"],
    productImplication: "Require credibility before recommending referral asks.",
    version: "principle.v1",
    active: true,
  },
  {
    id: "help-seekers-underestimate",
    title: "People often underestimate willingness to help",
    principle: "Help seekers may underestimate compliance and effort helpers will provide.",
    evidenceGrade: "B",
    evidenceType: "social psychology experiments",
    sourceTitle: "If you need help, just ask",
    sourceAuthors: "Flynn, Lake, Bohns, Newark",
    sourceYear: 2008,
    sourceIdentifier: "JPSP/OBHDP line of work",
    applicableContext: "user discomfort vs objective readiness",
    exceptions: ["boundaries, burden, and credibility still matter"],
    productImplication: "Separate user discomfort from social inappropriateness.",
    version: "principle.v1",
    active: true,
  },
  {
    id: "informational-interviews",
    title: "Informational conversations can support learning",
    principle: "Informational interviews are useful for learning, but should not be forced as a ritual.",
    evidenceGrade: "D",
    evidenceType: "career services guidance",
    sourceTitle: "MIT career development guidance",
    sourceAuthors: "MIT Career Advising",
    sourceYear: 2024,
    sourceIdentifier: "professional guidance",
    applicableContext: "role, company, function learning",
    exceptions: ["explicit referral offer should skip unnecessary info ritual"],
    productImplication: "Use as one interaction primitive, not mandatory sequence.",
    version: "principle.v1",
    active: true,
  },
];
