import { vector } from "@/config/model";
import type { Scenario } from "@/domain/types";

export const scenarioBank: Scenario[] = [
  {
    id: "scenario-cross-layer-debug",
    title: "Intermittent integrated-system failure",
    prompt: "A device fails only when hardware, software, sensors, and field workflow interact. You have logs, test equipment, and a week to isolate why.",
    targetDimensions: ["investigation_orientation", "evidence_density", "integration_preference", "real_system_grounding", "causal_reasoning"],
    positiveVector: vector({ investigation_orientation: 9.6, evidence_density: 9.1, integration_preference: 9.4, real_system_grounding: 9.2, causal_reasoning: 9.5 }),
    informationValue: 0.94,
    clarifiesRepellents: ["unclear ownership", "field ambiguity"],
  },
  {
    id: "scenario-requirements-orchestration",
    title: "Requirements and stakeholder alignment",
    prompt: "A broad product program has ambiguous requirements, many stakeholders, and no clear owner. Success means aligning teams and documenting tradeoffs.",
    targetDimensions: ["coordination_preference", "problem_structure", "customer_interaction_preference", "closure_preference"],
    positiveVector: vector({ coordination_preference: 9.2, problem_structure: 2.8, customer_interaction_preference: 8.4, closure_preference: 4.2 }),
    informationValue: 0.9,
    clarifiesRepellents: ["too much coordination", "ambiguity"],
  },
  {
    id: "scenario-documentation-protocol",
    title: "Routine validation evidence",
    prompt: "You execute predefined verification procedures, maintain traceability, document deviations, and prepare release evidence repeatedly.",
    targetDimensions: ["repetition_tolerance", "problem_structure", "coordination_preference", "experimentation_preference"],
    positiveVector: vector({ repetition_tolerance: 9.2, problem_structure: 9, coordination_preference: 6.8, experimentation_preference: 3.8 }),
    informationValue: 0.86,
    clarifiesRepellents: ["documentation", "routine verification"],
  },
  {
    id: "scenario-engineering-tool",
    title: "Automate engineering reconciliation",
    prompt: "Engineers spend hours reconciling logs, spreadsheets, and test outputs. You could build a tool that makes the workflow reliable.",
    targetDimensions: ["software_as_tool", "creation_style", "integration_preference", "measurable_feedback"],
    positiveVector: vector({ software_as_tool: 9.7, creation_style: 8.5, integration_preference: 8.4, measurable_feedback: 8.2 }),
    informationValue: 0.84,
    clarifiesRepellents: ["too much coding", "workflow ambiguity"],
  },
  {
    id: "scenario-customer-field",
    title: "Customer-site troubleshooting",
    prompt: "A customer is blocked by a technical failure. You travel onsite, reproduce the issue, gather evidence, and teach the customer how to recover.",
    targetDimensions: ["customer_interaction_preference", "real_system_grounding", "closure_preference", "investigation_orientation"],
    positiveVector: vector({ customer_interaction_preference: 9.6, real_system_grounding: 9.1, closure_preference: 8.7, investigation_orientation: 8.4 }),
    informationValue: 0.83,
    clarifiesRepellents: ["customer-facing", "travel"],
  },
  {
    id: "scenario-abstract-modeling",
    title: "Open-ended theoretical model",
    prompt: "Before useful testing can begin, you need to search literature and invent the governing model for a poorly understood phenomenon.",
    targetDimensions: ["theory_vs_application", "problem_structure", "measurable_feedback", "closure_preference"],
    positiveVector: vector({ theory_vs_application: 1.8, problem_structure: 2.5, measurable_feedback: 3.2, closure_preference: 3 }),
    informationValue: 0.82,
    clarifiesRepellents: ["too theoretical", "long uncertainty"],
  },
  {
    id: "scenario-algorithm-subgroup",
    title: "Sensor algorithm subgroup failure",
    prompt: "An existing sensor algorithm performs worse for a subgroup. You need to determine the mechanism and improve performance.",
    targetDimensions: ["evidence_density", "measurable_feedback", "experimentation_preference", "software_as_tool", "causal_reasoning"],
    positiveVector: vector({ evidence_density: 9.4, measurable_feedback: 9.1, experimentation_preference: 8.6, software_as_tool: 8.3, causal_reasoning: 8.7 }),
    informationValue: 0.88,
    clarifiesRepellents: ["unclear labels", "messy data"],
  },
  {
    id: "scenario-greenfield-product",
    title: "Blank-sheet product creation",
    prompt: "You have an open product space, unclear success criteria, user interviews, and freedom to invent a new direction.",
    targetDimensions: ["creation_style", "problem_structure", "customer_interaction_preference", "closure_preference"],
    positiveVector: vector({ creation_style: 9.3, problem_structure: 2.2, customer_interaction_preference: 8.6, closure_preference: 3.8 }),
    informationValue: 0.78,
    clarifiesRepellents: ["blank-sheet ambiguity"],
  },
];
