import { DIMENSION_IDS } from "@/config/model";
import type { DimensionId } from "@/domain/types";
import { PREFERENCE_PHRASES } from "@/lab/onetLab";
import { AUTONOMOUS_PREFERENCE_DIMENSIONS_V1 } from "@/lab/preferenceTarget";
import type { VirtualSubject } from "@/lab/types";
export interface MonotonicityResult {id:DimensionId;n:number;coverage:number;highEvidenceAssociation:number;lowEvidenceAssociation:number;observableSignalAssociation:number;signalByTruthQuartile:number[];monotonicBins:boolean;eligible:boolean;failures:string[]}
const mean=(x:number[])=>x.length?x.reduce((a,b)=>a+b,0)/x.length:0;
function corr(x:number[],y:number[]){const mx=mean(x),my=mean(y);const den=Math.sqrt(x.reduce((s,v)=>s+(v-mx)**2,0)*y.reduce((s,v)=>s+(v-my)**2,0));return den?x.reduce((s,v,i)=>s+(v-mx)*(y[i]!-my),0)/den:0;}
function has(texts:string[],phrases:string[]){return texts.some(t=>phrases.some(p=>t.toLowerCase().includes(p.toLowerCase())));}
export function assessGeneratorMonotonicity(subjects:VirtualSubject[]):MonotonicityResult[]{return DIMENSION_IDS.map(id=>{const truth=subjects.map(s=>s.truth.taskDnaTruth[id]);const high=subjects.map(s=>Number(has(s.observations.explicitPreferences,PREFERENCE_PHRASES[id][0])));const low=subjects.map(s=>Number(has(s.observations.explicitDislikes,PREFERENCE_PHRASES[id][1])));const signal=high.map((h,i)=>h-low[i]!);const bounds=[0,2.5,5,7.5,10.01];const bins=bounds.slice(0,-1).map((min,i)=>mean(signal.filter((_v,j)=>truth[j]!>=min&&truth[j]!<bounds[i+1]!)));const highAssociation=corr(truth,high),lowAssociation=corr(truth,low),observable=corr(truth,signal);/* finite seeded samples may jitter around zero in adjacent middle bins; 0.05 is declared tolerance, not a tuned score */const monotonicBins=bins.every((v,i)=>i===0||v+0.05>=bins[i-1]!);const eligible=AUTONOMOUS_PREFERENCE_DIMENSIONS_V1.includes(id);const failures=[...(highAssociation<=0?["high-pole evidence does not increase with truth"]:[]),...(lowAssociation>=0?["low-pole evidence does not decrease with truth"]:[]),...(!monotonicBins?["binned observable signal is non-monotone beyond 0.05 sampling tolerance"]:[])];return {id,n:subjects.length,coverage:signal.filter(x=>x!==0).length/subjects.length,highEvidenceAssociation:highAssociation,lowEvidenceAssociation:lowAssociation,observableSignalAssociation:observable,signalByTruthQuartile:bins,monotonicBins,eligible,failures};});}
export function eligibleMonotonicityPass(results:MonotonicityResult[]){return results.filter(r=>r.eligible).every(r=>r.coverage>0&&r.highEvidenceAssociation>0&&r.lowEvidenceAssociation<0&&r.observableSignalAssociation>0&&r.monotonicBins);}
