import type { OccupationSkeleton, OccupationalFamily } from "@/lab/types";

export const OCCUPATION_SOURCE = {
  name: "O*NET-inspired local snapshot",
  version: "onet-inspired.v1",
  licenseNote: "Locally versioned public occupational/task structure synthesized from publicly documented O*NET occupation titles, task patterns, and generalized work activities. Not a full O*NET download and not used as preference ground truth.",
} as const;

export const occupationSkeletons: OccupationSkeleton[] = [
  occ("17-2141.00", "Mechanical Engineers", "engineering_hardware", "manufacturing", ["Design mechanical systems and specify test methods", "Investigate component failures from field or lab evidence", "Coordinate with manufacturing on tolerances"], ["Analyzing data or information", "Making decisions and solving problems"], ["engineering design", "root cause", "test design"], ["mechanical", "materials"], ["precision", "time pressure"]),
  occ("17-2112.00", "Industrial Engineers", "engineering_hardware", "manufacturing", ["Analyze production bottlenecks with measurements", "Design experiments that improve yield or cycle time", "Document process changes"], ["Evaluating information to determine compliance", "Analyzing data"], ["statistics", "process improvement", "doe"], ["manufacturing"], ["repetitive measurement", "cross-team coordination"]),
  occ("15-1252.00", "Software Developers", "software_it", "software", ["Build and maintain application features", "Review code and debug production incidents", "Integrate APIs and data stores"], ["Working with computers", "Thinking creatively"], ["typescript", "apis", "debugging"], ["software"], ["sprint cadence", "ambiguous requirements"]),
  occ("15-1212.00", "Information Security Analysts", "software_it", "cybersecurity", ["Investigate security incidents from logs and alerts", "Contain and document attack paths", "Recommend control changes"], ["Identifying objects, actions, and events", "Analyzing data"], ["incident response", "log analysis", "communication"], ["cybersecurity"], ["on-call", "incomplete evidence"]),
  occ("15-2051.00", "Data Scientists", "data_analytics", "analytics", ["Frame questions from messy datasets", "Build models and evaluate error by cohort", "Communicate limitations to stakeholders"], ["Analyzing data or information", "Interpreting the meaning of information"], ["python", "statistics", "data visualization"], ["analytics"], ["unclear labels", "long analysis cycles"]),
  occ("19-1042.00", "Medical Scientists", "scientific_research", "healthcare", ["Design studies and interpret experimental results", "Write protocols and papers", "Investigate unexpected findings"], ["Updating and using relevant knowledge", "Analyzing data"], ["research", "statistics", "experimentation"], ["biology", "clinical research"], ["long feedback loops", "grant constraints"]),
  occ("29-1141.00", "Registered Nurses", "healthcare_professional", "healthcare", ["Assess patients and prioritize interventions", "Document clinical status and handoffs", "Coordinate with physicians and families"], ["Assisting and caring for others", "Documenting/recording information"], ["clinical workflow", "communication", "triage"], ["nursing"], ["shift work", "emotional load"]),
  occ("11-9111.00", "Medical and Health Services Managers", "healthcare_operations", "healthcare operations", ["Coordinate staffing and throughput", "Review quality metrics and exceptions", "Translate policy into unit practice"], ["Coordinating the work and activities of others", "Making decisions"], ["operations", "quality systems", "stakeholder management"], ["healthcare administration"], ["meetings", "regulatory documentation"]),
  occ("13-2051.00", "Financial and Investment Analysts", "finance", "finance", ["Build forecasts and variance explanations", "Test assumptions against new evidence", "Present tradeoffs to decision makers"], ["Analyzing data", "Getting information"], ["financial modeling", "excel", "forecasting"], ["finance"], ["close calendar", "ambiguous strategy asks"]),
  occ("13-2011.00", "Accountants and Auditors", "accounting_audit", "accounting", ["Reconcile accounts and test exceptions", "Prepare audit evidence packages", "Explain control gaps"], ["Evaluating information to determine compliance", "Documenting information"], ["accounting", "audit", "excel"], ["accounting"], ["deadline clusters", "repetitive close work"]),
  occ("13-1111.00", "Management Analysts", "consulting", "consulting", ["Interview stakeholders about a broken process", "Structure findings and options", "Facilitate decisions across owners"], ["Getting information", "Communicating with people outside the organization"], ["stakeholder management", "communication", "analysis"], ["consulting"], ["travel", "ambiguous problem statements"]),
  occ("11-2021.00", "Marketing Managers", "product", "product", ["Prioritize a roadmap from customer and revenue evidence", "Negotiate scope across teams", "Write decision records"], ["Making decisions", "Communicating with supervisors, peers, or subordinates"], ["roadmaps", "customer interviews", "prioritization"], ["product"], ["ambiguity", "stakeholder churn"]),
  occ("13-1082.00", "Project Management Specialists", "project_program", "operations", ["Build plans and track dependencies", "Run status and risk reviews", "Unblock owners when work stalls"], ["Scheduling work and activities", "Communicating with supervisors"], ["project management", "communication", "risk tracking"], ["program management"], ["status overhead", "unclear authority"]),
  occ("13-1081.00", "Logisticians", "operations_supply", "supply chain", ["Track shipments and inventory exceptions", "Reroute when a node fails", "Measure on-time performance"], ["Monitoring processes", "Making decisions"], ["logistics", "excel", "exception handling"], ["supply chain"], ["firefighting", "vendor delays"]),
  occ("41-4012.00", "Sales Representatives, Wholesale and Manufacturing", "sales", "sales", ["Qualify customer problems and budget", "Negotiate terms and close decisions", "Maintain account relationships"], ["Selling or influencing others", "Establishing and maintaining relationships"], ["negotiation", "customer interviews", "communication"], ["sales"], ["quota pressure", "rejection"]),
  occ("13-1161.00", "Market Research Analysts", "marketing", "marketing", ["Design surveys or interviews", "Analyze campaign or segment performance", "Recommend positioning changes"], ["Analyzing data", "Interpreting information"], ["statistics", "customer interviews", "communication"], ["marketing"], ["noisy attribution", "stakeholder taste fights"]),
  occ("13-1071.00", "Human Resources Specialists", "hr_recruiting", "hr", ["Source and screen candidates", "Coordinate interviews and offers", "Advise managers on process"], ["Communicating with people outside the organization", "Resolving conflicts"], ["recruiting", "communication", "stakeholder management"], ["human resources"], ["ambiguous scorecards", "volume screening"]),
  occ("23-1011.00", "Lawyers", "legal_compliance", "legal", ["Research precedent and draft arguments", "Advise clients on risk", "Negotiate or litigate outcomes"], ["Getting information", "Evaluating information"], ["research", "writing", "negotiation"], ["law"], ["long cycles", "adversarial context"]),
  occ("13-1041.00", "Compliance Officers", "legal_compliance", "compliance", ["Interpret policy and collect proof", "Document findings for audit", "Train teams on required controls"], ["Evaluating information to determine compliance", "Documenting information"], ["documentation", "audit", "policy"], ["compliance"], ["evidence requests", "rule ambiguity"]),
  occ("25-2031.00", "Secondary School Teachers", "education", "education", ["Plan lessons and assess learning", "Adapt explanations for different students", "Coordinate with families and staff"], ["Training and teaching others", "Coaching and developing others"], ["curriculum design", "communication", "assessment"], ["education"], ["classroom load", "uneven feedback"]),
  occ("15-1255.00", "Web and Digital Interface Designers", "ux_design", "ux", ["Interview users and map pain points", "Prototype interfaces and test them", "Translate findings into design changes"], ["Thinking creatively", "Getting information"], ["figma", "ux research", "customer interviews"], ["design"], ["taste debates", "thin research time"]),
  occ("43-4051.00", "Customer Service Representatives", "customer_success", "customer success", ["Diagnose a blocked customer from incomplete tickets", "Restore service and document the pattern", "Escalate recurring product defects"], ["Assisting and caring for others", "Resolving conflicts"], ["communication", "troubleshooting", "ticketing"], ["service"], ["volume", "limited authority"]),
  occ("49-2094.00", "Electrical and Electronics Repairers", "field_technical", "field service", ["Troubleshoot equipment onsite", "Replace modules and verify recovery", "Capture field evidence for engineering"], ["Repairing and maintaining electronic equipment", "Inspecting equipment"], ["troubleshooting", "instrumentation", "customer communication"], ["field service"], ["travel", "customer escalation"]),
  occ("11-3012.00", "Administrative Services Managers", "public_sector", "public sector", ["Coordinate vendors and internal service requests", "Maintain records and procurement evidence", "Translate policy into office practice"], ["Organizing, planning, and prioritizing work", "Communicating with supervisors"], ["documentation", "procurement", "coordination"], ["public administration"], ["process load", "slow approval cycles"]),
];

function occ(
  onetCode: string,
  title: string,
  family: OccupationalFamily,
  industry: string,
  tasks: string[],
  generalizedWorkActivities: string[],
  skills: string[],
  knowledge: string[],
  workContext: string[],
): OccupationSkeleton {
  return { onetCode, title, family, industry, tasks, generalizedWorkActivities, skills, knowledge, workContext, source: "onet-inspired-local-snapshot" };
}

export const families: OccupationalFamily[] = Array.from(new Set(occupationSkeletons.map((occupation) => occupation.family)));
